MACOSX_SDK_VERSION:  # [osx and x86_64]
  - 10.15            # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.14"                # [osx and x86_64]

c_compiler:
- vs2019 # [win]
cxx_compiler:
- vs2019 # [win]
openssl:
- '1.1.1'
- '3'
- '3'
curl:
- 7
- 7
- 8
gcs:
- gcs_disabled
- gcs_disabled
- gcs_enabled
zip_keys:
- gcs
- openssl
- curl
